# Generated by Django 5.1 on 2024-08-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="products_meli",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idShopi", models.CharField(max_length=20)),
                ("idPublicationMeli", models.CharField(max_length=20)),
                ("title", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "idVariantShopi",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "pricePublication",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                ("sku", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
