# Generated by Django 4.2.6 on 2025-11-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrdersFullfilment",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=50, null=True)),
                ("ecomerce", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "customer_email",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
    ]
