# Generated by Django 4.2.6 on 2025-11-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordersfullfilment",
            name="customer_email",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="ordersfullfilment",
            name="customer_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="ordersfullfilment",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
