# Generated by Django 4.2.6 on 2023-10-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quote_print", "0002_remove_quote_id_shopi_remove_quote_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="cursor",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
