# Generated by Django 4.2.6 on 2023-10-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quote_print", "0003_quote_cursor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="customer",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
