# Generated by Django 4.2.6 on 2023-10-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quote_print", "0004_alter_quote_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="total",
            field=models.IntegerField(default=0, verbose_name=False),
        ),
    ]
