# Generated by Django 4.2.6 on 2024-09-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quote_print", "0005_quote_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="customer",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
