# Generated by Django 4.2.6 on 2024-11-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quote_print", "0006_alter_quote_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="SigoToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=1400, null=True)),
                ("date_expired", models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name="quote",
            name="seller",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
