# Generated by Django 4.2.6 on 2024-11-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quote_print", "0007_sigotoken_quote_seller"),
    ]

    operations = [
        migrations.CreateModel(
            name="SigoCostumers",
            fields=[
                (
                    "id",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("identification", models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name="sigotoken",
            name="token",
            field=models.CharField(max_length=1400),
        ),
    ]
