# Generated by Django 4.2.6 on 2024-12-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quote_print", "0008_sigocostumers_alter_sigotoken_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="nit",
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
