# Generated by Django 4.2.6 on 2024-12-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quote_print", "0009_quote_nit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="nit",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
