# Generated by Django 4.2.6 on 2025-01-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quote_print", "0010_alter_quote_nit"),
    ]

    operations = [
        migrations.CreateModel(
            name="SodimacOrders",
            fields=[
                (
                    "id",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("status", models.BooleanField(default=False)),
            ],
        ),
    ]
