# Generated by Django 4.2.6 on 2025-01-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quote_print", "0011_sodimacorders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sodimacorders",
            name="status",
            field=models.CharField(max_length=20),
        ),
    ]
