# Generated by Django 4.2.6 on 2025-01-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quote_print", "0012_alter_sodimacorders_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sodimacorders",
            name="status",
            field=models.CharField(default="1-PENDIENTE", max_length=20),
        ),
    ]
