# Generated by Django 4.2.6 on 2025-01-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quote_print", "0013_alter_sodimacorders_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sodimacorders",
            name="factura",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
