# Generated by Django 4.2.6 on 2025-01-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quote_print", "0014_sodimacorders_factura"),
    ]

    operations = [
        migrations.AddField(
            model_name="sodimacorders",
            name="date_invoice",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sodimacorders",
            name="novelty",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
