# Generated by Django 4.2.6 on 2025-01-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quote_print", "0015_sodimacorders_date_invoice_sodimacorders_novelty"),
    ]

    operations = [
        migrations.CreateModel(
            name="SodimacKits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kitnumber", models.CharField(max_length=50)),
                ("sku", models.CharField(max_length=50)),
                ("quantity", models.IntegerField(default=0)),
            ],
        ),
    ]
