# Generated by Django 4.2.6 on 2025-02-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quote_print", "0016_sodimackits"),
    ]

    operations = [
        migrations.AddField(
            model_name="sodimacorders",
            name="value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
