# Generated by Django 4.2.6 on 2025-07-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quote_print", "0017_sodimacorders_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="sodimacorders",
            name="oc_shopify",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
