# Generated by Django 4.2.6 on 2026-03-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quote_print", "0019_quote_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sodimacorders",
            name="oc_shopify",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
