# Generated by Django 4.2.6 on 2026-04-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_print', '0020_alter_sodimacorders_oc_shopify'),
    ]

    operations = [
        migrations.AddField(
            model_name='sodimackits',
            name='ean',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
