# Generated by Django 4.2.6 on 2026-04-10 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quote_print', '0021_sodimackits_ean'),
    ]

    operations = [
        migrations.AddField(
            model_name='sodimacorders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sodimacorders',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sodimacorders',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
