# Generated by Django 4.2.6 on 2026-04-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_print', '0022_sodimacorders_created_at_sodimacorders_total_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sodimacorders',
            name='last_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
