# Generated by Django 4.2.6 on 2026-04-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_print', '0023_sodimacorders_last_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sodimacorders',
            name='fecha_transmision',
            field=models.DateField(blank=True, null=True),
        ),
    ]
