# Generated by Django 4.2.6 on 2023-12-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SKU", models.CharField(blank=True, max_length=50, null=True)),
                ("RF_pamo", models.CharField(blank=True, max_length=50, null=True)),
                ("Indicador", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
