# Generated by Django 4.2.6 on 2023-12-05 03:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pamo_bots", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Products",
            new_name="ProductsSodimac",
        ),
    ]
