# Generated by Django 4.2.6 on 2024-06-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pamo_bots", "0003_productssodimac_cod_barras"),
    ]

    operations = [
        migrations.AddField(
            model_name="productssodimac",
            name="stok",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
