# Generated by Django 4.2.6 on 2024-06-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pamo_bots", "0004_productssodimac_stok"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogBotOrders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
                ("get_orders", models.BooleanField()),
                ("description", models.CharField(max_length=50)),
                ("error", models.BooleanField()),
                ("log", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="productssodimac",
            old_name="stok",
            new_name="stock",
        ),
    ]
