# Generated by Django 4.2.6 on 2024-06-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pamo_bots", "0005_logbotorders_rename_stok_productssodimac_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logbotorders",
            name="description",
        ),
        migrations.AlterField(
            model_name="logbotorders",
            name="log",
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
