# Generated by Django 4.2.6 on 2024-07-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pamo_bots", "0006_remove_logbotorders_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productssodimac",
            name="stock_sodi",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
