# Generated by Django 4.2.6 on 2024-07-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pamo_bots", "0007_productssodimac_stock_sodi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productssodimac",
            name="RF_pamo",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="productssodimac",
            name="SKU",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="productssodimac",
            name="cod_barras",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
