# Generated by Django 4.2.6 on 2024-09-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pamo_bots", "0009_rename_cod_barras_productssodimac_ean_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productssodimac",
            name="sku_pamo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
