# Generated by Django 4.2.6 on 2025-06-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pamo_bots", "0010_alter_productssodimac_sku_pamo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productssodimac",
            name="ean",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
