# Generated by Django 4.2.6 on 2025-07-31 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pamo_bots", "0011_alter_productssodimac_ean"),
    ]

    operations = [
        migrations.AddField(
            model_name="logbotorders",
            name="oc_shopify",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
