# Generated by Django 4.2.6 on 2025-07-31 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pamo_bots", "0012_logbotorders_oc_shopify"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logbotorders",
            name="oc_shopify",
        ),
    ]
