# Generated by Django 4.2.6 on 2026-02-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pamo_bots", "0013_remove_logbotorders_oc_shopify"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productssodimac",
            name="sku_pamo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
