# Generated by Django 4.2.6 on 2026-04-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamo_bots', '0014_alter_productssodimac_sku_pamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicesSiigo',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('items_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('oc', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
