# Generated by Django 4.2.6 on 2026-04-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamo_bots', '0015_invoicessiigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicessiigo',
            name='novelty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
