# Generated by Django 4.2.6 on 2026-05-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamo_bots', '0016_invoicessiigo_novelty'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicessiigo',
            name='seller',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
