# Generated by Django 4.2.6 on 2026-05-22 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pamo_bots', '0017_invoicessiigo_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersShopify',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pedido', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pamo_bots.ordersshopify')),
            ],
        ),
    ]
