# Generated by Django 4.2.6 on 2026-05-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamo_bots', '0018_ordersshopify_productsorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersshopify',
            name='cursor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productsorders',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
