# Generated by Django 4.2.6 on 2026-05-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamo_bots', '0019_ordersshopify_cursor_productsorders_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursor', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordersshopify',
            name='cursor',
        ),
    ]
