# Generated by Django 4.2.6 on 2026-05-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamo_bots', '0020_lastcursor_remove_ordersshopify_cursor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersshopify',
            name='shipping_company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordersshopify',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ordersshopify',
            name='url_traking',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
