# Generated by Django 4.2.6 on 2026-05-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamo_bots', '0021_ordersshopify_shipping_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersshopify',
            name='tracking_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
