# Generated by Django 4.2.6 on 2026-05-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamo_bots', '0022_ordersshopify_tracking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersshopify',
            name='url_traking',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
