# Generated by Django 4.2.6 on 2026-05-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamo_bots', '0023_alter_ordersshopify_url_traking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersshopify',
            name='url_traking',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
