# Generated by Django 4.2.6 on 2026-05-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamo_bots', '0024_alter_ordersshopify_url_traking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersshopify',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
