# Generated by Django 4.2.6 on 2026-06-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamo_bots', '0025_alter_ordersshopify_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersshopify',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordersshopify',
            name='in_transit',
            field=models.BooleanField(default=False),
        ),
    ]
