# Generated by Django 4.2.6 on 2026-06-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamo_bots', '0026_ordersshopify_comments_ordersshopify_in_transit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersshopify',
            name='tracking_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
