# Generated by Django 4.2.6 on 2026-06-12 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pamo_bots', '0027_alter_ordersshopify_tracking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersshopify',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='ordersshopify',
            name='in_transit',
        ),
        migrations.RemoveField(
            model_name='ordersshopify',
            name='tracking_status',
        ),
        migrations.CreateModel(
            name='TrakingOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_status', models.CharField(blank=True, max_length=20, null=True)),
                ('in_transit', models.BooleanField(default=False)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traking', to='pamo_bots.ordersshopify')),
            ],
        ),
    ]
