# Generated by Django 4.2.6 on 2026-06-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamo_bots', '0028_remove_ordersshopify_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersshopify',
            name='tracking_number',
        ),
        migrations.RemoveField(
            model_name='ordersshopify',
            name='url_traking',
        ),
        migrations.AddField(
            model_name='trakingorders',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trakingorders',
            name='url_traking',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
