# Generated by Django 4.2.6 on 2026-06-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamo_bots', '0029_remove_ordersshopify_tracking_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trakingorders',
            name='shipping_company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
