# Generated by Django 4.2.6 on 2026-06-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pamo_bots', '0030_trakingorders_shipping_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersshopify',
            name='shipping_company',
        ),
    ]
