# Generated by Django 4.2.6 on 2026-06-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamo_bots', '0031_remove_ordersshopify_shipping_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersshopify',
            name='order_is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
