# Generated by Django 4.2.6 on 2026-07-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamo_bots', '0032_ordersshopify_order_is_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trakingorders',
            name='shipping_company',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='trakingorders',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
