# Generated by Django 4.2.6 on 2026-07-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamo_bots', '0033_alter_trakingorders_shipping_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trakingorders',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
