# Generated by Django 4.2.6 on 2026-07-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamo_bots', '0034_alter_trakingorders_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trakingorders',
            name='id_fulfilments',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='trakingorders',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
