# Generated by Django 4.2.6 on 2026-07-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamo_bots', '0035_trakingorders_id_fulfilments_alter_trakingorders_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trakingorders',
            name='id_fulfilments',
            field=models.CharField(max_length=50),
        ),
    ]
