# Generated by Django 4.2.6 on 2023-10-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("tags", models.CharField(max_length=500)),
                ("proveedor", models.CharField(blank=True, max_length=100, null=True)),
                ("price", models.IntegerField(default=0, verbose_name=False)),
                ("compareAtPrice", models.IntegerField(default=0, verbose_name=False)),
                ("sku", models.CharField(blank=True, max_length=100, null=True)),
                ("barcode", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "inventoryQuantity",
                    models.IntegerField(default=0, verbose_name=False),
                ),
            ],
        ),
    ]
