# Generated by Django 4.2.6 on 2023-12-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=300, null=True)),
                ("tags", models.CharField(blank=True, max_length=500, null=True)),
                ("vendor", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                ("price", models.FloatField(blank=True, default=0, null=True)),
                ("compareAtPrice", models.FloatField(blank=True, default=0, null=True)),
                ("sku", models.CharField(blank=True, max_length=100, null=True)),
                ("barcode", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "inventoryQuantity",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("cursor", models.CharField(blank=True, max_length=80, null=True)),
                ("margen", models.FloatField(blank=True, default=0, null=True)),
                ("costo", models.FloatField(blank=True, default=0, null=True)),
                (
                    "margen_comparacion_db",
                    models.FloatField(blank=True, default=0, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaveMargins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("margen", models.FloatField(blank=True, default=0, null=True)),
                ("costo", models.FloatField(blank=True, default=0, null=True)),
                (
                    "margen_comparacion_db",
                    models.FloatField(blank=True, default=0, null=True),
                ),
            ],
        ),
    ]
