# Generated by Django 4.2.6 on 2023-11-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="proveedor",
            new_name="vendor",
        ),
        migrations.AddField(
            model_name="products",
            name="cursor",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
