# Generated by Django 4.2.6 on 2024-03-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="idShopi",
            field=models.CharField(default="", max_length=20),
        ),
    ]
