# Generated by Django 4.2.6 on 2023-11-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_rename_proveedor_products_vendor_products_cursor"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
