# Generated by Django 4.2.6 on 2024-06-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_products_idshopi"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="ean",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="stok_sodimac",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
