# Generated by Django 4.2.6 on 2023-11-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_products_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="tags",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
