# Generated by Django 4.2.6 on 2024-06-22 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_products_ean_products_stok_sodimac"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="ean",
        ),
    ]
