# Generated by Django 4.2.6 on 2023-11-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_products_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="margen",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
