# Generated by Django 4.2.6 on 2024-06-22 18:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_remove_products_ean"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="stok_sodimac",
        ),
    ]
