# Generated by Django 5.1 on 2024-08-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_remove_products_stok_sodimac"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="idVariantShopi",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
