# Generated by Django 4.2.6 on 2024-09-05 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_products_idvariantshopi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="idVariantShopi",
        ),
    ]
