# Generated by Django 4.2.6 on 2023-11-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_products_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaveMargins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "margen",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
            ],
        ),
    ]
