# Generated by Django 4.2.6 on 2023-11-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_savemargins"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="costo",
            field=models.IntegerField(default=0, verbose_name=False),
        ),
    ]
