# Generated by Django 4.2.6 on 2023-11-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_products_costo"),
    ]

    operations = [
        migrations.AddField(
            model_name="savemargins",
            name="costo",
            field=models.IntegerField(default=0, verbose_name=False),
        ),
    ]
