# Generated by Django 4.2.6 on 2023-11-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_savemargins_costo"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="margen_comparacion_db",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="savemargins",
            name="margen_comparacion_db",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
